version: '3.5'
services:
  webapp-server :
    hostname: websphere
    image: websphere-liberty:webProfile6
    ports:
      - "9080:9080"
    volumes:
      - ./web-application/target/webapp-example.war:/config/dropins/webapp-example.war
      - ./service-loader/target/service-scheduler.war:/config/dropins/camel-example.war
    depends_on:
      - oracle-db
  oracle-db :
    hostname: oradb
    image: oracle/database:11.2.0.2-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=admin
    shm_size: '2gb'
    volumes:
      - oracledb:/u01/app/oracle/oradata
      - ./docker-entrypoint.sh:/unlock-hr.sh
volumes:
  oracledb: